# Auto-generated by tournament.py
# This file defines short-name wrapper agents.

from __future__ import annotations

from AgeAgeAgent import AgeAgeAgent as _BaseAgent0

class Age(_BaseAgent0):
    pass

from scml_agents.scml2025.standard.team_276.litaagent_std.litaagent_ys import LitaAgentYS as _BaseAgent1

class LYS(_BaseAgent1):
    pass

from scml_agents.scml2025.standard.team_280.price_trend import PriceTrendStdAgent as _BaseAgent2

class Pri(_BaseAgent2):
    pass

from scml_agents.scml2025.standard.team_254.ultra import UltraSuperMiracleSoraFinalAgentZ as _BaseAgent3

class Ult(_BaseAgent3):
    pass

from scml_agents.scml2025.standard.team_276.litaagent_std.litaagent_n import LitaAgentN as _BaseAgent4

class LtN(_BaseAgent4):
    pass

from scml_agents.scml2024.standard.team_178.ax import AX as _BaseAgent5

class AX(_BaseAgent5):
    pass

from scml_agents.scml2024.standard.coyoteteam.group2 import Group2 as _BaseAgent6

class Gro(_BaseAgent6):
    pass

from scml_agents.scml2024.standard.teamyuzuru.quick_decision_agent import QuickDecisionAgent as _BaseAgent7

class Qui(_BaseAgent7):
    pass

from scml_agents.scml2025.standard.team_276.litaagent_std.litaagent_p import LitaAgentP as _BaseAgent8

class LtP(_BaseAgent8):
    pass

from scml_agents.scml2025.standard.team_276.litaagent_std.litaagent_cirs import LitaAgentCIRS as _BaseAgent9

class LRS(_BaseAgent9):
    pass

from scml_agents.scml2025.standard.team_268.optimistic_agent import OptimisticAgent as _BaseAgent10

class Opt(_BaseAgent10):
    pass

from scml_agents.scml2024.standard.team_181.dogagent import DogAgent as _BaseAgent11

class Dog(_BaseAgent11):
    pass

from scml_agents.scml2025.standard.team_255.proactive_agent import ProactiveAgent as _BaseAgent12

class Pro(_BaseAgent12):
    pass

from scml_agents.scml2024.standard.team_atsunaga.S24s import S5s as _BaseAgent13

class S5s(_BaseAgent13):
    pass

from scml_agents.scml2025.standard.team_255.myagent import PonponAgent as _BaseAgent14

class Pon(_BaseAgent14):
    pass

from scml_agents.scml2025.standard.team_268.katsudon_agent import KATSUDONAgent as _BaseAgent15

class KAT(_BaseAgent15):
    pass

from scml_agents.scml2024.standard.team_193.matching_pennies import MatchingPennies as _BaseAgent16

class Mat(_BaseAgent16):
    pass

from scml_agents.scml2025.standard.team_276.litaagent_std.litaagent_cir import LitaAgentCIR as _BaseAgent17

class LIR(_BaseAgent17):
    pass

from scml_agents.scml2025.standard.team_253.master_sota_agent import XenoSotaAgent as _BaseAgent18

class Xen(_BaseAgent18):
    pass

__all__ = [
    "Age",
    "LYS",
    "Pri",
    "Ult",
    "LtN",
    "AX",
    "Gro",
    "Qui",
    "LtP",
    "LRS",
    "Opt",
    "Dog",
    "Pro",
    "S5s",
    "Pon",
    "KAT",
    "Mat",
    "LIR",
    "Xen",
]
